# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_auto_20160921_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bind_hosts',
            field=models.ManyToManyField(blank=1, to='hosts.BindHostToUser'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='host_groups',
            field=models.ManyToManyField(blank=1, to='hosts.HostGroup'),
        ),
    ]
